### ISSUE TITLE
extreme gain values in the beta parameter of the pRF retinotopy model fit

### ISSUE THREAD

**Issue by rosemary-le** [vistalab/vistasoft#127]
The majority of these values lie between 0 and 1 ... but why are there some values on the order of 10^10?

(If I understand it correctly, the first beta weight is the gain, i.e. the amplitude of the predicted time series).

**Comment by JWinawer** [comment]
Hi Rosemary.

Two quick notes. First, many of the values of gain should be ignored, as they will apply to voxels with poor pRF fits. 

But even if you limit the voxels to 'good voxels', you will see a wide range of gain values, larger than the range of % BOLD responses observed across voxels. 

One reason is that the pRF definition is a 2D Gaussian with unit height, not unit volume. This means that when you take the dot product of, say, a full-field stimulus and a pRF, the the result depends on sigma (the bigger the sigma, the bigger the product). Because the observed BOLD signal does not scale this way, the gain shows the opposite trend - it is smaller as the sigma gets larger. 

I illustrated this with a sample Matlab script. Just change the first line to specify the path to one of your models, and it should run. 

%% CODE START %%%%%%%%%%%%%%%%%%%%%%%%%%
load('Gray/Averages Bars/retModel-20140113-173158-fFit-fFit.mat')
%%

% model solutions
m = model{1};

% stimulus radius (in degrees)
stimRadius = params.stim(1).stimSize;

% model parameters
varexp = rmGet(m, 'varexp');
gain   = rmGet(m, 'amplitude comp1');
sigma  = rmGet(m, 'sigma major');
ecc    = rmGet(m, 'ecc');

% limit to good voxels
keepInds = varexp > .3 & ...        ignore low variance explained    
    sigma > .1 * stimRadius & ...   ignore very small sigma
    ecc + 1*sigma < stimRadius; ... require voxels have at least +/- 1 sd inside stimulus extent
    
%% Look at sigma v gain
% PRFs are defined to have unit height (not unit volume). Hence volume
% scales with the square of the standard deviation**. Assuming a constant
% bold response across voxels, then the pRF amplitude should square
% inversely with the square of the standard deviation. So sigma v gain is
% linear on a log / log plot 
%   gain      = c*sigma.^2
%   log(gain) = log(c*sigma.^2)
%   log(gain) = log(c) + log(sigma.^2)
%   log(gain) = C + 2*log(sigma)
%
% ** An except is for pRFs which have large fractions outside the stimulus
% extent. Here our estimates of both size and gain are likely to be
% innacurate, and we should not try to account for them.

% plot sigma versus gain on linear axes
figure; 
scatter(sigma(keepInds), gain(keepInds)); 
xlabel('sigma major (deg)'); ylabel('gain')

% plot sigma versus gain on log-log axes
figure
scatter(sigma(keepInds), gain(keepInds)); 
set(gca, 'XScale', 'log', 'YScale', 'log');
xlabel('sigma major (deg)'); ylabel('gain')

% fit a line on log-log axes
p = polyfit(log(sigma(keepInds)),log(gain(keepInds)), 1);
pred = polyval(p, log(sigma(keepInds)));
hold on;
plot(sigma(keepInds), exp(pred), 'k-');
str = sprintf('log(Y) = %3.1f log(X)+%3.1f', p(1), p(2));
text(median(sigma(keepInds)), max(exp(pred)), str, 'FontSize', 20, 'Color', 'k')

**Comment by rosemary-le** [comment]
Ah I see. Earlier I had been thresholding for variance explained (only around .1 or so -- I guess this could have been higher as well) but not excluding voxels with very low sigmas ... which would explain the extremely high gain values. 

Thank you for the explanation. The script gave me a lot of insight!
