### ISSUE TITLE
Relative vs. Absolute path in dataTYPES

### ISSUE THREAD

**Issue by htakemur** [vistalab/vistasoft#146]
When I am running mrVista, in many cases, dataTYPES stores the location of the files in the absolute path:

For example,
dataTYPES(1).scanParams.inplanePath = /project/data/humandata/subject1/raw/8bars_run1.nii.gz;

However, in some cases, we need to copy the folder storing mrVista session to other folder (e.g. exporting the mrVista data to other computer). In that case, now I need to rewrite the path to those files again because dataTYPES defines the location of folder and files in absolute path. 

Do you think that it is worth considering to use relative path, instead of abslote path, to define the location of files and folders in dataTYPES in mrVista code (perhaps we need to change somewhere around mrInit)? Or, are there any existing codes for doing that?

**Comment by JWinawer** [comment]
It would be great to edit the code to make it use relative paths. One way
to handle this would be to change the code in sessionGet and dtGet viewGet,
so that regardless of how the path is stored, the code that looks up the
path converts it to a relative path. Changes could also be made in the set
codes so that paths are stored as relative paths. But just changing the get
codes alone should fix the functionality, I think.



On Wed, Dec 2, 2015 at 3:09 AM, Hiromasa Takemura <notifications@github.com>
wrote:

> When I am running mrVista, in many cases, dataTYPES stores the location of
> the files in the absolute path:
>
> For example,
> dataTYPES(1).scanParams.inplanePath =
> /project/data/humandata/subject1/raw/8bars_run1.nii.gz;
>
> However, in some cases, we need to copy the folder storing mrVista session
> to other folder (e.g. exporting the mrVista data to other computer). In
> that case, now I need to rewrite the path to those files again because
> dataTYPES defines the location of folder and files in absolute path.
>
> Do you think that it is worth considering to use relative path, instead of
> abslote path, to define the location of files and folders in dataTYPES in
> mrVista code (perhaps we need to change somewhere around mrInit)? Or, are
> there any existing codes for doing that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vistalab/vistasoft/issues/146>.
>



-- 
Jonathan Winawer
Assistant Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/

**Comment by JWinawer** [comment]
A recent change to mrInit now preserves relative paths for functional data and inplane data when initializing a session (assuming you supply relative paths). This should help with this issue, at least for new projects.
