### ISSUE TITLE
Is there any way to avoid alignment when anatomical and functional images perfectly match?

### ISSUE THREAD

**Issue by ahmadi123** [vistalab/vistasoft#149]
Dear mrVista experts,
We have acquired a high resolution EPI image (instead of T1 image) with the same slice, resolution and same refrence frame as functional images within the same session. (voxel size= 0.65 mm isotropic, slices =41). We got this image to avoid losing information by interpolation caused by alignment of anatomical to functional image. 
It isn't possible to install white/gray segmentation and open gray view afterwards without having 4x4transformation matrix of alignment. Seting a field of zeros(4) or ones(4) as alignment matrix in mr.SESSION file gave me an error about Chol command. So, I had to call rxAlign. after manual editting, I receive the following matrix: 
mrSESSION.alignment=[-0.0327   -0.0025   -0.9995   44.8402; 0.9994   -0.0097   -0.0327    1.9135;
    0.0096    1.0000   -0.0028   -0.7513; 0     0         0    1.0000] 
and at the end, meshes don't look allright. Is there any way to skip alignment ?
Any help is greatly appreciated. 
Best regards,
Khazar Ahmadi

**Comment by JWinawer** [comment]
If I understand your situation, you have a high resolution EPI, and you
would like to use this EPI both as the inplane anatomy underlay, and as the
volume anatomy. If so, then this is a good problem for a validation script.
You would think it would be easy, but it is not. The reason is, mrVista
uses a particular convention for showing slice data (e.g., left side of
brain on left, slices in third dimension), and a different convention for
the anatomical underlay (IPR).

I started to write a script to show how this works and to do the test
situation you describe, in which the identical scan is used for the inplane
underlay and the volume anatomy. I have not finished it. The last part is
hard. WHen I do finish, I will add it to the vistatest respository as
validation code. Meantime, what I started does do a few useful things, and
is copied below in case you want to look at it, or in case someone wants to
finisih it.

You need the vistadata svn repository on your path to run this.

% go the sammple data
dataDir = fullfile(mrvDataRootPath,'functional','mrBOLD_01');
cd(dataDir);

% initialize a hidden inplane
ip = initHiddenInplane; ip = loadAnat(ip);

% find the inplane nifti
ipPath = sessionGet(mrSESSION, 'inplane path');

% get the transform used for the inplane
xformNifti2ip = niftiCreateXform(niftiRead(ipPath), 'inplane');

% check that we did inplane xform correctly
ni = niftiApplyXform(niftiRead(ipPath), xformNifti2ip);
figure, colormap gray, set(gcf,'name', 'Inplane')
subplot(2,1,1), imagesc(ip.anat.data(:,:,1)), axis image; title('from
mrvista')
subplot(2,1,2), imagesc(ni.data(:,:,1)), axis image; title('from nifti')


% set the volume anatomy to match the inplane anatomy
vANATOMYPATH = ipPath;

% re-save
save('mrSESSION.mat', 'vANATOMYPATH', '-append');

% load a gray view and get the vANATOMY xform
gr = initHiddenGray; gr = loadAnat(gr);

% when loading the volume anatomy, mrVista first orients to RAS
[niRAS, xformNifti2Can] = niftiApplyCannonicalXform(niftiRead(ipPath));
assert(isequal(niftiCurrentOrientation(niRAS), 'RAS'));

% then mrVista transforms from canonical (RAS) to mrVista volume
orientation (IPR)
xformCan2Gray  = niftiCreateXformBetweenStrings('RAS','IPR');

% combine canonical and mrv to get total xform from raw nifti to gray
xformNifti2Gray =  xformCan2Gray * xformNifti2Can;

% check that we did gray xform correct
ni = niftiApplyXform(niftiRead(ipPath), xformNifti2Gray);
figure, colormap gray, set(gcf,'name', 'Volume')
subplot(2,1,1), imagesc(gr.anat(:,:,1)), axis image; title('from mrvista')
subplot(2,1,2), imagesc(ni.data(:,:,1)), axis image; title('from nifti')

% get the transform from mrvista inplane to mrvista gray, which means
invert nifti to inplane, and
% multiple by gray xform
xformIp2Gray = xformNifti2Gray * inv(xformNifti2ip) ;

% check that these agree
ip2gray = niftiApplyXform(ip.anat, xformIp2Gray);
figure, colormap gray, set(gcf,'name', 'Volume')
subplot(2,1,1), imagesc(gr.anat(:,:,1)), axis image; title('gray')
subplot(2,1,2), imagesc(ip2gray.data(:,:,1)), axis image; title('inplane to
gray')

% last problem is to translate xform in mm to xform in image indices, which
is the format used by mrVista
%
%
********************************************************************************
% NOT YET DONE - we need to convert xformIp2Gray to a transform in image
indices
%
********************************************************************************
%
% xformNew = ... ?
%
% % set the alignment
% mrSESSION = sessionSet(mrSESSION, 'alignment', xformNew);
%
% % resave
% save('mrSESSION.mat', 'mrSESSION', 'vANATOMYPATH', '-append');


On Wed, Dec 9, 2015 at 10:55 AM, AhmadiKh <notifications@github.com> wrote:

> Dear mrVista experts,
> We have acquired a high resolution EPI image (instead of T1 image) with
> the same slice, resolution and same refrence frame as functional images
> within the same session. (voxel size= 0.65 mm isotropic, slices =41). We
> got this image to avoid losing information by interpolation caused by
> alignment of anatomical to functional image.
> It isn't possible to install white/gray segmentation and open gray view
> afterwards without having 4x4transformation matrix of alignment. Seting a
> field of zeros(4) or ones(4) as alignment matrix in mr.SESSION file gave me
> an error about Chol command. So, I had to call rxAlign. after manual
> editting, I receive the following matrix:
> mrSESSION.alignment=[-0.0327 -0.0025 -0.9995 44.8402; 0.9994 -0.0097
> -0.0327 1.9135;
> 0.0096 1.0000 -0.0028 -0.7513; 0 0 0 1.0000]
> and at the end, meshes don't look allright. Is there any way to skip
> alignment ?
> Any help is greatly appreciated.
> Best regards,
> Khazar Ahmadi
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vistalab/vistasoft/issues/149>.
>



-- 
Jonathan Winawer
Assistant Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/

**Comment by ahmadi123** [comment]
Dear Prof.Winawer,
Many thanks for your reply and helpful explanation about the script. I was also impressed by your talk recently in Utrecht ! :) 
 Maybe, I wasn't so clear in my writing. The inplane underlay and volume anatomy are different images. Inplane anatomy is the middle volume of the first functional scan and EPI which was used as volume anatomy has exactly the same voxel size,slices and matrix size of inplane file acquired in the same session. The only difference is that EPI has higher TI=500ms. This was done to improve white/gray contrast and consequently enhace segmentation. 
Since these are 2 differnet images, I tried the script on my dataset as well and replaced VANATOMYPATH with ipPath in later lines of the code where the second was used. Checking the last figures shows agreement. Meanwhile, I will also try to deal with the last part (transformation in terms of image indices).
Thanks a lot for your help.
Warm regards,
Khazar Ahmadi

**Comment by JWinawer** [comment]
Perhaps your question was much simpler than what I understood. (But I am
still not sure.) Is your issue that your inplane underlay is simply the
first volume (or the mean volume) of your functional data? If so, then this
is a very easy problem to deal with. Vistasoft already assumes that your
functional data is aligned to your inplane underlay. Hence you do not need
to do anything to align them.

You still need to align the inplane underlay to the 3d volume anatomy.

Jon

On Fri, Dec 11, 2015 at 7:55 AM, AhmadiKh <notifications@github.com> wrote:

> Dear Prof.Winawer,
> Many thanks for your reply and helpful explanation about the script. I was
> also impressed by your talk recently in Utrecht ! :)
> Maybe, I wasn't so clear in my writing. The inplane underlay and volume
> anatomy are different images. Inplane anatomy is the middle volume of the
> first functional scan and EPI which was used as volume anatomy has exactly
> the same voxel size,slices and matrix size of inplane file acquired in the
> same session. The only difference is that EPI has higher TI=500ms. This was
> done to improve white/gray contrast and consequently enhace segmentation.
> Since these are 2 differnet images, I tried the script on my dataset as
> well and replaced VANATOMYPATH with ipPath in later lines of the code where
> the second was used. Checking the last figures shows agreement. Meanwhile,
> I will also try to deal with the last part (transformation in terms of
> image indices).
> Thanks a lot for your help.
> Warm regards,
> Khazar Ahmadi
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vistalab/vistasoft/issues/149#issuecomment-163930727>.
>



-- 
Jonathan Winawer
Assistant Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/
