### ISSUE TITLE
How to best import vistatest repository into vistasoft?

### ISSUE THREAD

**Issue by JWinawer** [vistalab/vistasoft#160]
Currently, vistatest is a git repository that runs vistasoft validation tests. I would like to import this repository into a subfolder in vistasoft. The question is, how to do it? 

One way is to just copy the files. This is a little cumbersome, and also loses the history of the vistatest commits. The history is not that important, so maybe this is ok.

But if there is a simple and more elegant way, please let me know.

Here is an example I found by Googling: http://www.nomachetejuggling.com/2011/09/12/moving-one-git-repo-into-another-as-subdirectory/

-Jon

**Comment by arokem** [comment]
I think that it's OK to just copy over all the files into the
sub-directory, add that entire directory and move on. The trick in that
blog-post is clever, but it also has a misleading element, because it
pretends that you were doing the work inside of a subdirectory called
`old-project` all along. That might be more confusing than not having the
history...

If you want to preserve history, we can do that by adding a note pointing
to the deprecated repository in a README file in the new test directory.
Either way, you'll want to plaster a big warning on the old repo, that
tells people that it has been incorporated into vistasoft and that they
should not to use that one, to avoid any confusion.

Another option is to make vistatest a submodule of vistasoft (
https://git-scm.com/book/en/v2/Git-Tools-Submodules), but I think this is
actually not a good use-case for that, and will just add unnecessary
complexity. I just wanted to add that for completeness - I am not
advocating that!

**Comment by JWinawer** [comment]
OK, I will just copy over files. I don't think anyone will need the history
of vistatest edits. Thanks for checking up on the blog post suggestion.

Jon

On Sun, Jan 24, 2016 at 7:40 PM, Ariel Rokem <notifications@github.com>
wrote:

> I think that it's OK to just copy over all the files into the
> sub-directory, add that entire directory and move on. The trick in that
> blog-post is clever, but it also has a misleading element, because it
> pretends that you were doing the work inside of a subdirectory called
> `old-project` all along. That might be more confusing than not having the
> history...
>
> If you want to preserve history, we can do that by adding a note pointing
> to the deprecated repository in a README file in the new test directory.
> Either way, you'll want to plaster a big warning on the old repo, that
> tells people that it has been incorporated into vistasoft and that they
> should not to use that one, to avoid any confusion.
>
> Another option is to make vistatest a submodule of vistasoft (
> https://git-scm.com/book/en/v2/Git-Tools-Submodules), but I think this is
> actually not a good use-case for that, and will just add unnecessary
> complexity. I just wanted to add that for completeness - I am not
> advocating that!
>
>
> On Sun, Jan 24, 2016 at 1:34 PM, Jonathan Winawer <
> notifications@github.com>
> wrote:
>
> > Assigned #160 <https://github.com/vistalab/vistasoft/issues/160> to
> > @arokem <https://github.com/arokem>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vistalab/vistasoft/issues/160#event-524363212>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vistalab/vistasoft/issues/160#issuecomment-174357128>.
>



-- 
Jonathan Winawer
Assistant Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/
