### ISSUE TITLE
using RDT with vistasoft example data set

### ISSUE THREAD

**Issue by JWinawer** [vistalab/vistasoft#163]
The addition of RemoteDataToolbox will be useful. But I am having some trouble using it with the example functional data set that was added. 

For example, the code below produces an error. Does anyone know why?
```
rd = RdtClient('vistasoft');
rd.crp('/functional');
a = rd.listArtifacts;
data = rd.readArtifact(a(1).artifactId);
```

_Error using gradleFetchArtifact (line 136)
fetchPom Could not resolve all dependencies for configuration ':fetchPom'.
fetchWithClassifier Could not resolve all dependencies for configuration ':fetchWithClassifier'.
fetchWithoutClassifier Could not resolve all dependencies for configuration ':fetchWithoutClassifier'.

Error in rdtReadArtifact (line 50)
[localPath, pomPath, downloads] = gradleFetchArtifact(configuration.repositoryUrl, ...

Error in RdtClient/readArtifact (line 150)
            [data, artifact, downloads] = rdtReadArtifact(obj.configuration, ..._

**Comment by wandell** [comment]
I think I understand the issue, and I believe the software has to do better. 

I believe the error is this.  We need to include the file type in the rd.readArtifact argument (default type is 'mat').  The file we are retrieving is an nii.gz (I think), which we do specify.  I have made this mistake several times, and I think many people will.  

Worse yet,I tried to classify the type as 'gz', which is how it appears in the web browser, but I the download still did not work.  So, I suspect that we do not a method for handling files with the 'nii.gz' extension.

Rather than me trying to debug this, I will alert Ben Heasly to the issue over on the RemoteDataToolbox repository.  He is very efficient and will surely get back in a couple of days.

**Comment by wandell** [comment]
@JWinawer I just completed the review of the pull request from Ben.  I think this issue will now be resolved.

The script t_rdtExample.m in vistasoft/rdt describes how to read data from the archiva repository.  I will try to write a wiki page tutorial today.  I am going to close this Issue.  Perhaps we should move to one of the test routines, and work through that together in a separate issue.
