### ISSUE TITLE
ms vs. s for framePeriod (TR)

### ISSUE THREAD

**Issue by tommysprague** [vistalab/vistasoft#189]
In much of the RF model-fitting code (e.g., defining the onset times of each stimulus frame), it appears necessary to use seconds as the unit of time. This is also true for all GLM-type analyses, as far as I can tell. 

However, it seems as though the TR is saved in the dataTYPES and mrSESSION variables as milliseconds. At least for GLM code (the "new version", as described[ here](https://web.stanford.edu/group/vista/cgi-bin/wiki/index.php/Event-Related)), the framePeriod parameter is pulled from the dataTYPES session variable. This causes problems when computing a design matrix. 

I propose we either:
1. stick to s or ms throughout (would involve adding a check to niftiRead and/or mrInit.m to see whether the framePeriod is too long - e.g., > 1000, and dividing by 1000)
2. adjust GLM code (many functions, including glmConvolve.m, glmCreateDesignMtx.m, glm_hrf.m, among others) to perform this check/adjustment when loading a dataTYPE

my temporary fix was to manually update the framePeriod field of the current dataTYPE, but I imagine this may cause problems elsewhere.

**Comment by JWinawer** [comment]
The TR is meant to be saved in dataTYPES and mrSESSION variables as seconds, not milliseconds. The likely reason that it appeared to be saved in milliseconds had to do with a bug in how readNifti used to deal with units under some conditions. This was fixed in a separate issue. Please re-open the issue if the problem re-emerges.
