### ISSUE TITLE
MATLAB CRASHES when installing gray/white classification file

### ISSUE THREAD

**Issue by marco-create** [vistalab/vistasoft#324]
Hello experts,
I use MATLAB 2019 on a windows 10 machine.
I'm working on my retinotopy project and trying to perform pRF analysis using vistasoft.
The issue happens when, opening mrVista with the inplane image mounted, I click on "Gray" | Gray/White segmentation | Install or reinstall segmentation.
I install the classification image (NIFTI) but when the process starts I get the an error that obliges me to close and restart MATLAB.
Please, have a look at the file error. It has been saved automatically by MATLAB.

[matlab_crash_dump.4044-1.txt](https://github.com/vistalab/vistasoft/files/4040538/matlab_crash_dump.4044-1.txt)

Thank you in advance for the help! I don't know how to proceed receiving this error.
Marco

**Comment by JWinawer** [comment]
It looks like the grow_gray mex file caused a crash. You could try to recompile it. You might also try running the validation script for installing a segmentation: test_installSegmentation

Note that the first time you run this, it will take a long time (at least a few minutes), since it will need to first download the validation data sets, which can be large. If this runs without error, then there might be a problem with your segmentation file. But if this fails too, then it's more likely a problem with the mex file, as indicated above. 

If you solve the problem, please close the issue.

Jon

**Comment by marco-create** [comment]
I finally performed the gray installation on MATLAB on Linux machine (Virtual Machine) using the [code from this tutorial](https://github.com/vistalab/vistasoft/blob/master/tutorials/bold/session/t_installSegmentation.m) adjusted to my files.

Every time I try to run this process on Windows MATLAB, it crashes. On MATLAB on Linux Virtual Machine, it works properly.
