### ISSUE TITLE
nearpoints.c MEX file trouble

### ISSUE THREAD

**Issue by shmp0722** [vistalab/vistasoft#338]
Hi Vasta members

I have a mex file trouble. When using required nearpoints.c function from dtiIntersectFibersWithRoi, this error returns

Invalid MEX-file '/home/ganka/git/vistasoft/mrAnatomy/mex/nearpoints.mexa64':
/home/ganka/MATLAB/R2015b/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by
/home/ganka/git/vistasoft/mrAnatomy/mex/nearpoints.mexa64)

I updated gcc 9.2.0 or 10.?.? and added PATH to bashrc or bash_profile as LD_LIBRARY_PATH. But Matlab seems to read own library.

Any suggestions or advice will be appreciated.

My setting is 
Red Hat Enterprise Linux Workstation release 6.8 (Santiago)
Matlab 2015b
gcc (GCC) 9.2.0

**Comment by htakemur** [comment]
I think that this is likely because there will be a mismatch of a version of libstdc++.so.6 which MATLAB linked, and a version of libstdc++.so.6 which Mex-file linked. I had a very similar issue when I attempted to load ANTs from MATLAB. 

Suggestions:
(Option 1) Test newer MATLAB version, which will links to different version of libstdc++.so.6 

(Option 2) Type following comment, before starting your MATLAB: 

`'LD_PRELOAD=**full path to libstdc++.so.6 to use**'`

LD_PRELOAD enables the use of specific environmental variables and libraries.

**Comment by shmp0722** [comment]
Two options htakemura suggested did not work for my setting. But updated Matlab resolved the MEX file trouble.  

Thank you for advice.
