### ISSUE TITLE
event related time course UI

### ISSUE THREAD

**Issue by dmochow** [vistalab/vistasoft#84]
When trying to plot time course UI from a scan group, the 'params' field is being taken from the 'Original' data type and NOT the 'GLM' data type:

Taken from er_voxelData.m:

% ras,  04/05.
verbose = prefsVerboseCheck;

% get params,  trials,  coords
data.trials = er_concatParfiles(view, scans);
data.params = er_getParams(view, scans(1)); % assume all scans have same params
if preserveCoords==0
    data.coords = double(roiSubCoords(view, roi.coords)); %, scans(1))); % remove redundant voxels
else
    data.coords = double(roi.coords);
end

**Comment by JWinawer** [comment]
Well, this issue is 4 years old and probably resolved. But just in case, here is the answer to the question:

The function er_voxelData uses whatever dataTYPE is currently set. It neither assumes this is 'Original', nor 'GLM'. The user has to set it.

An example usage is in the test function, 
``` matlab
test_glm();
```
which first sets the dataTYPE (line 55), then gets the Event Related parameters:

``` matlab
% set to motion comp dataTYPES
vw = viewSet(vw, 'current data type', dataType);

% get the GLM params
params = er_getParams(vw, scans(1), dataType);
```

Since the test function passes, I am closing the issue.
